### ISSUE TITLE
hack chat

### ISSUE THREAD

**Issue by SolarFlare1524** [highfl/-blooket-hacks#1]
i tried but it didn't work

**Comment by highfl** [comment]
It wont give you a plus account, but it lets you use the plus account benefits. For example, since live hosting is currently down and only available for plus members, you can use the javascript and then it will give you access to hosting.
[Recording11.webm](https://user-images.githubusercontent.com/112288957/195186848-bb62b47d-553c-45da-9ec4-ad284715b2f9.webm)

**Comment by SolarFlare1524** [comment]
can you try and make the blook access define the user

**Comment by SolarFlare1524** [comment]
and thanks for the plus benifits

**Comment by highfl** [comment]
What do you mean by 'define the user'? Do you want me to make one that lets you see what blooks other people have in game?

**Comment by highfl** [comment]
Also, I will be adding scripts for the other gamemodes as well, but it might take a little bit. I will try to have them up by this weekend

**Comment by highfl** [comment]
You're welcome btw

**Comment by SolarFlare1524** [comment]
thx

**Comment by SolarFlare1524** [comment]
it says undefined i mean

**Comment by highfl** [comment]
Hmm. I'll send you a video of me using it. Perhaps you are using it in the wrong place?

**Comment by SolarFlare1524** [comment]
ok

**Comment by SolarFlare1524** [comment]
when will you message me it?

**Comment by highfl** [comment]
Im making it right now

**Comment by SolarFlare1524** [comment]
ok (:

**Comment by highfl** [comment]
Here you go. You have to make it in game
[Recording13.webm](https://user-images.githubusercontent.com/112288957/195217926-dfaebc09-c230-4680-a055-ef3a3547d728.webm)

**Comment by highfl** [comment]
Try it now after watching the video. Also i will be right back

**Comment by highfl** [comment]
Did it work

**Comment by SolarFlare1524** [comment]
thanks i will try it now

**Comment by SolarFlare1524** [comment]
thx it worked and i was doing it wrong

**Comment by SolarFlare1524** [comment]
you should try to make a gui

**Comment by highfl** [comment]
Sure! I will try to make it

**Comment by SolarFlare1524** [comment]
i will definitely use it if you do, so good luck!

**Comment by highfl** [comment]
I put a GUI that I didn't make up. The global hacks don't work, but what it does is when you are in a specific gamemode, it will give you hacks that you can click related to that gamemode. For example, if you were in factory, it would give you buttons that you can press that would allow you to set your cash, get rid of glitches, give you mega bots, I.E.

**Comment by highfl** [comment]
You can use that in the meantime while I make my own

**Comment by SolarFlare1524** [comment]
ok thx

**Comment by highfl** [comment]
Also, can you please star this project

**Comment by highfl** [comment]
I added more hacks for the gamemodes

**Comment by SolarFlare1524** [comment]
thanks for the update👍

**Comment by SolarFlare1524** [comment]
(:

**Comment by SolarFlare1524** [comment]
how you going with izt (:

**Comment by SolarFlare1524** [comment]
hi

**Comment by highfl** [comment]
solar are you there?

**Comment by highfl** [comment]
I added more things

**Comment by SolarFlare1524** [comment]
ok thx i live in australia so i was sleeping

**Comment by highfl** [comment]
hacks for blooket?

**Comment by SolarFlare1524** [comment]
yeah

**Comment by SolarFlare1524** [comment]
btw the gui global doesn't work as of the new update

**Comment by highfl** [comment]
yeah i know im working on another one that should work

**Comment by highfl** [comment]
the other one wasn't made by me btw it was just one that i found that you can use in the meantime

**Comment by SolarFlare1524** [comment]
ok, I can't wait for your one!

**Comment by highfl** [comment]
thanks! hopefully it should be up by this weekend or next week!

**Comment by SolarFlare1524** [comment]
ok, Can't wait!

**Comment by highfl** [comment]
All of the hacks for the other gamemodes are up!

**Comment by SolarFlare1524** [comment]
thx

**Comment by highfl** [comment]
how are u

**Comment by highfl** [comment]
are they working for you

**Comment by SolarFlare1524** [comment]
yes and they work well
🍑🍆🍎🥭🥭🍍🍉👍🤣❤🤣🍋🍍🍍

**Comment by SolarFlare1524** [comment]
my recents

**Comment by highfl** [comment]
?

**Comment by highfl** [comment]
what does that mean

**Comment by highfl** [comment]
hi im bored

**Comment by SolarFlare1524** [comment]
i have to go for a bit but i will be back soon

**Comment by highfl** [comment]
hi

**Comment by SolarFlare1524** [comment]
hi

**Comment by highfl** [comment]
arre the hacks working well for you

**Comment by SolarFlare1524** [comment]
yes they are

**Comment by highfl** [comment]
Great! The GUI should be up this weekend!

**Comment by SolarFlare1524** [comment]
ok (:

**Comment by highfl** [comment]
Hellleoo
